### ISSUE TITLE
stable?

### ISSUE THREAD

**Issue by glycerine** [Harvey-OS/ninep#21]
Hello Ron,

I'm a gopher looking to play with 9p2000 in Go. This looks like the only recently active Go library that implements the protocol. Could you comment on its production readiness/status?  

The open PR makes it sound like some serious experimentation is underway, but perhaps there are parts that are stable and usable?

- Jason

**Comment by rminnich** [comment]
I've been using it for quite some time now and it's been very solid and stable.
I appreciate PRs and improvements ;-)

**Comment by glycerine** [comment]
Thanks, and that is great to hear. I'm looking forward to doing some experiments with it.
